### PR TITLE
Update change stream example comments

### PR DESCRIPTION
**Pull request by saghm**

### CODE REVIEW

**Comment by kay-kim** [comment]
@saghm  -- just wondering if this can be merged

**Comment by saghm** [comment]
Oops, sorry this fell off my radar! It looks like a couple things failed in Evergreen; although I'm pretty sure they're unrelated, I think I should take a closer look and figure out what's going on.

Worst case scenario, Emily is back next week and can help me debug any issues that are still going on.

**Comment by saghm** [comment]
Given that these changes are so trivial, we can just merge this, as it would take me longer than we have until Emily comes back to get everything on the Evergreen build green again.

**Comment by estolfo** [comment]
thanks @saghm 
I'm back and can take care of getting Evergreen builds green. Thanks = )

**Pull request merged**
