### PR TITLE
RUBY-2296: Fix app metadata spec

### PR DESCRIPTION
**Pull request by comandeo**
This commit fixes an assumption that the spec is always executed on a
Linux machine.

### CODE REVIEW

**Review by p-mongo — COMMENTED** [review]
Unfortunately this test now lost all of the explicit assertions on what data is actually ending up in the metadata document. For example, if cpu/platform are empty it would still pass.

Can the original test be left as is and skipped if OS isn't linux and a new test be added which asserts specific values for mac instead?

**Comment by comandeo** [comment]
We can do that; however, in this case we will have more or less same problems with `architecture` attribute.  Ideally we need to create a test for every supported combination of OS/CPU type. I am not sure if it worth it, though.

My assumption was that we if `RbConfig::CONFIG` is not complete, there is not much we can do anyway, so we can rely on it. On the other hand, I do understand your reasons.

**Comment by p-mongo** [comment]
For now I think two cases would be sufficient: the existing one which works in Evergreen and hopefully on all of the (at least mainstream) linux distributions, and one which works on your machine which would hopefully work on all apple products.

**Comment by p-mongo** [comment]
I would also like to see the values that the driver will use for the metadata fields on apples, right now this isn't in the test.

**Review by p-mongo — APPROVED** [review]

**Pull request merged**
