### PR TITLE
DOCS-7775 Update compatibility matrix for 2.3

### PR DESCRIPTION
**Pull request by estolfo**

### CODE REVIEW

**Comment by pedrosnk** [comment]
Is this driver fully compatible with ruby 2.3.x (MRI) ?

**Comment by estolfo** [comment]
Yes, that's what our compatibility matrix shows: https://docs.mongodb.com/ruby-driver/master/reference/driver-compatibility/

Are you finding otherwise?

**Comment by pedrosnk** [comment]
Thanks a lot for the answer.

I only found this other matrix https://docs.mongodb.com/ruby-driver/master/installation/ only I was a little concerned.

**Comment by estolfo** [comment]
oh! Sorry about the confusion. We'll update that as well.

**Pull request merged**
