### PR TITLE
[Ruby-3510] Add Ruby-3.3 to testing matrix

### PR DESCRIPTION
**Pull request by adviti-mishra**
Added Ruby-3.3 to the testing matrix for the Ruby Driver per [this ticket](https://jira.mongodb.org/browse/RUBY-3510?workflowName=DBX+Teams+-+Non-Epics+-+Workflow&stepId=13)

### CODE REVIEW

**Comment by jamis** [comment]
This looks promising! Sadly, there's always a danger when updating the Ruby version, and we're running into some of that here. There are several of the tests that are failing on 3.3. It looks like Ruby 3.3 changed the exception that is raised when a socket cannot resolve a hostname:

```bash
$ ruby -v -rsocket -e 'TCPSocket.new("bogus.address", 1000)'
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
-e:1:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from -e:1:in `new'
	from -e:1:in `<main>'
$ ruby -v -rsocket -e 'TCPSocket.new("bogus.address", 1000)'
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
-e:1:in `initialize': getaddrinfo: nodename nor servname provided, or not known (Socket::ResolutionError)
	from -e:1:in `new'
	from -e:1:in `<main>'
```

The tests (at least?) are explicitly looking for `SocketError`, which isn't robust enough here.

**Review by jamis — CHANGES_REQUESTED** [review]
(See my previous comment.)

**Comment by kalicki** [comment]
up! News?

**Comment by jamis** [comment]
Hey @kalicki -- this is still in progress but ran into some roadblocks related to our testing infrastructure. Stay tuned.

**Comment by jamis** [comment]
We can't officially guarantee 3.3 support until we have CI running it, but FWIW, I do most of my development on it using 3.3. *Caveat emptor*, and all that.

**Comment by jamis** [comment]
Fixed in #2902

**Pull request closed without merging**
