### PR TITLE
RUBY-2678 Add updated spec tests

### PR DESCRIPTION
**Pull request by comandeo**

### CODE REVIEW

**Comment by comandeo** [comment]
Specs are copied from this PR - https://github.com/mongodb/specifications/pull/990

**Comment by p-mongo** [comment]
This diff obliterates chromium, but looking at it on the console:

 The json files should be deleted, we do not use them

The template files should be deleted, they are used only in the specs repo to generate the yaml files

Can you please make one PR for file moves and another one for newly added files

**Comment by p-mongo** [comment]
https://github.com/mongodb/specifications/pull/990 isn't merged?

**Comment by comandeo** [comment]
> [mongodb/specifications#990](https://github.com/mongodb/specifications/pull/990) isn't merged?

No, it's not. Actually, this PR was made to check whether new spec tests are passing in a driver. Actually, now I think we should not merge this PR, but rather wait until specs are merged.

**Comment by alcaeus** [comment]
> Actually, now I think we should not merge this PR, but rather wait until specs are merged.

I agree. The idea was to verify that the new tests are correct. We can resume working on this once the PR is merged.

**Comment by comandeo** [comment]
Converting to a draft to make it explicitly not mergeable.

**Pull request closed without merging**
