### PR TITLE
RUBY-1038: Implement Read Concern for 3.2

### PR DESCRIPTION
**Pull request by durran**

### CODE REVIEW

**Comment by behackett** [comment]
Read concern is supposed to be a Collection level option.

https://github.com/mongodb/specifications/blob/master/source/read-write-concern/read-write-concern.rst#location-specification

**Comment by durran** [comment]
It's a client, database, AND collection level option (as well as operation level)... I haven't handled that yet - only the operation level ones which is why this is still marked as WIP.

**Comment by behackett** [comment]
Do we allow passing write concern per operation?

**Comment by durran** [comment]
Spec states: "a driver MAY allow it to be specified on a per-operation basis in accordance with the CRUD specification" - and the driver ticket has them per command as well for those we provide helpers for. (https://jira.mongodb.org/browse/DRIVERS-254)

**Comment by durran** [comment]
Oh sorry - you said write concern... Yes we do on some operations.

**Comment by behackett** [comment]
As long as we're being consistent.

**Comment by durran** [comment]
Actually I just double checked and we pull it from collection. Good catch then - I'll change these to do the same.

**Comment by behackett** [comment]
Great. Thanks!

**Pull request merged**
