### PR TITLE
Timeout::Error is inconsistent with other uses of Mongo::Error::SocketTimeoutError.

### PR DESCRIPTION
**Pull request by reidmorrison**
Somewhere along the line the exception class name changed from Mongo::Error::SocketTimeoutError to Timeout::Error. This PR restores the original behavior.

### CODE REVIEW

**Comment by estolfo** [comment]
Hi @reidmorrison 
Would you be able to share a code example showing the previous behavior?
I'm guessing this change happened with this commit: https://github.com/mongodb/mongo-ruby-driver/commit/ea8a33b34ccb1ca814edc8d916f77e3555403536

handle_errors was catching the Errno::ETIMEDOUT before. I'm thinking maybe we want to change #handle_errors instead to catch the error thrown in read_from_socket instead of just restoring the error class to SocketTimeoutError.

**Comment by reidmorrison** [comment]
Below is the exception we see in production. It causes confusion because it is raising the generic Timeout::Error that is used by the builtin Ruby Timeout class.

~~~
Timeout::Error·Took more than 300 seconds to receive data
vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/socket.rb:181:in `read_from_socket': Took more than 300 seconds to receive data. (Timeout::Error)
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/socket.rb:123:in `block in read'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/socket.rb:199:in `handle_errors'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/socket.rb:122:in `read'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/protocol/message.rb:117:in `deserialize'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/server/connectable.rb:114:in `block in read'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/server/connectable.rb:97:in `ensure_connected'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/server/connectable.rb:113:in `read'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/server/connection.rb:163:in `deliver'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/server/connection.rb:108:in `block in dispatch'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/monitoring/publishable.rb:47:in `publish_command'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/server/connection.rb:107:in `dispatch'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/operation/executable.rb:37:in `block in execute'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/server/connection_pool.rb:107:in `with_connection'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/server.rb:242:in `with_connection'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/operation/executable.rb:35:in `execute'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/collection/view/iterable.rb:81:in `send_initial_query'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/collection/view/iterable.rb:41:in `block in each'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/retryable.rb:43:in `read_with_retry'
    from vendor/bundle/jruby/2.3.0/bundler/gems/mongo-ruby-driver-168daf9c2c0d/lib/mongo/collection/view/iterable.rb:39:in `each'
    from vendor/bundle/jruby/2.3.0/gems/mongoid-5.2.0/lib/mongoid/query_cache.rb:221:in `each'
    from vendor/bundle/jruby/2.3.0/gems/mongoid-5.2.0/lib/mongoid/contextual/mongo.rb:129:in `each'
    from vendor/bundle/jruby/2.3.0/gems/mongoid-5.2.0/lib/mongoid/contextual.rb:20:in `each'
    from org/jruby/RubyEnumerable.java:459:in `to_a'
    from vendor/bundle/jruby/2.3.0/gems/mongoid-5.2.0/lib/mongoid/criteria/findable.rb:107:in `from_database'
    from vendor/bundle/jruby/2.3.0/gems/mongoid-5.2.0/lib/mongoid/criteria/findable.rb:75:in `multiple_from_db'
    from vendor/bundle/jruby/2.3.0/gems/mongoid-5.2.0/lib/mongoid/criteria/findable.rb:19:in `execute_or_raise'
    from vendor/bundle/jruby/2.3.0/gems/mongoid-5.2.0/lib/mongoid/criteria/findable.rb:40:in `find'
    from vendor/bundle/jruby/2.3.0/gems/mongoid-5.2.0/lib/mongoid/findable.rb:94:in `find'
~~~

The purpose of this PR is to ensure that the Mongo Driver raises its own Mongo exceptions instead of the default exception used by the Ruby Timeout class.

**Comment by estolfo** [comment]
Thanks for the additional information @reidmorrison. I'm afraid changing the class will be a breaking change for users who might be catching the Timeout::Error; however, if this was the previous behavior, it's a bug and we should restore it. Have you taken a look at the test failure in travis? https://travis-ci.org/mongodb/mongo-ruby-driver/jobs/220638755

**Comment by reidmorrison** [comment]
Ok, will leave new Timeout error class

**Comment by estolfo** [comment]
Hi @reidmorrison 
We should change it if it was previous behavior. Was a SocketTimeoutError thrown before for the scenarios you are finding now throw a Timeout::Error?

**Pull request closed without merging**
