### PR TITLE
RUBY-1704 Create collections with write concern majority in transacti…

### PR DESCRIPTION
**Pull request by saghm**
…ons spec tests

### CODE REVIEW

**Comment by saghm** [comment]
I ran the transactions tests locally to ensure that nothing failed; the evergreen run is ongoing

**Comment by p-mongo** [comment]
I meant that this is the correct way of passing the write concern, since tests were passing without write concern being passed as well.

**Comment by saghm** [comment]
The driver doesn't do any handling of the write concern here; it's an option for the [`create` command](https://docs.mongodb.com/manual/reference/command/create/), so it gets passed verbatim to the server. If you're asking if the driver correctly passes options passed in command documents to the server, then yes, it does.

**Comment by p-mongo** [comment]
OK thanks.

**Comment by p-mongo** [comment]
@saghm Merge?

**Comment by saghm** [comment]
Will do

**Pull request merged**
