### PR TITLE
RUBY-1999 test assume role temporary credentials


### PR DESCRIPTION
**Pull request by p-mongo**

### CODE REVIEW

**Comment by ShaneHarvey** [comment]
At first glance I would expect this PR to add the "AssumeRole" spec test: https://github.com/mongodb/specifications/blob/master/source/auth/tests/mongodb-aws.rst#4assumerole

But I don't think that's the case because it's not using the aws_e2e_assume_role.js script. Can you explain what this change is testing?

**Comment by p-mongo** [comment]
This PR verifies that the driver is able to authenticate with temporary credentials (obtained from an assume role request, but could potentially be any temporary credentials) that are provided in the environment. 

The credentials are obtained via the tooling described in https://github.com/mongodb/mongo-ruby-driver/blob/master/spec/README.aws-auth.md#temporary-credentials---assumerole-request. It performs the function of the `aws_e2e_assume_role.js ` script but is also usable in other scenarios, for example it can be used in a local Docker container to obtain the temporary credentials.

**Comment by ShaneHarvey** [comment]
Can you point me to the MONGODB-AWS auth code (the code that runs `{saslStart: 1, mechanism: 'MONGODB-AWS', ...}`)?

**Comment by p-mongo** [comment]
That is a couple of PRs out.

**Comment by p-mongo** [comment]
So the authentication functionality that is currently in master is the request class which can make STS requests and sign requests for the server. There isn't a way to authenticate to the server yet.

**Pull request merged**
