### PR TITLE
Convert if else conditional to ternary for brevity

### PR DESCRIPTION
**Pull request by aayushagrawal135**
Converting boolean if else conditional to ternary operator conditional

### CODE REVIEW

**Comment by aayushagrawal135** [comment]
@egiurleo @p-mongo This is my first time contributing. Evergreen asks me to manually authorize the patch, how must i do this?

**Comment by egiurleo** [comment]
@aayushagrawal135 Thanks for your contribution! I authorized the patch for you, so the tests will be running against your changes.

**Comment by aayushagrawal135** [comment]
While running the tests in local with rake, i started a mongo server in a different terminal as mentioned in the docs. I am getting a _Mongo::Error::NoServerAvailable_ error for 1 test case. Could you help here?

**Comment by egiurleo** [comment]
@aayushagrawal135 I'm happy to help you if you let me know which commands you ran and which tests failed.

**Comment by aayushagrawal135** [comment]
@egiurleo I first ran `mkdir /tmp/mdb`,  `mongod --dbpath /tmp/mdb` in one terminal.
Then, ran `rake` in another.

Doing so, the test case `attempts to use IPv6 and fallbacks to IPv4` in `address_spec.rb` broke.
It was expecting `127.0.0.1` but it got `::2`

**Comment by egiurleo** [comment]
@aayushagrawal135 What's the output of running `ifconfig` on your machine? Also, could you copy and paste the entire error message and stack trace for the error you're experiencing? Thanks. :)

**Comment by aayushagrawal135** [comment]
```
 Mongo::Address#socket when providing a DNS entry that resolves to both IPv6 and IPv4 attempts to use IPv6 and fallbacks to IPv4
     Failure/Error: raise Unauthorized.new(user, full_mechanism)
     
     Mongo::Auth::Unauthorized:
       User root-user (mechanism: scram) is not authorized to access ruby-driver (used mechanism: SCRAM-SHA-1) (on localhost:27017) (on localhost:27017)
     # ./lib/mongo/auth/scram/conversation.rb:522:in `validate!'
     # ./lib/mongo/auth/scram/conversation.rb:516:in `validate_first_message!'
     # ./lib/mongo/auth/scram/conversation.rb:112:in `continue'
     # ./lib/mongo/auth/scram.rb:73:in `login'
     # ./lib/mongo/server/connection.rb:368:in `block in authenticate!'
     # ./lib/mongo/server.rb:437:in `handle_auth_failure!'
     # ./lib/mongo/server/connection.rb:366:in `authenticate!'
     # ./lib/mongo/server/connection.rb:190:in `do_connect'
     # ./lib/mongo/server/connection.rb:171:in `connect!'
     # ./lib/mongo/server/connection_pool.rb:731:in `connect_connection'
     # ./lib/mongo/server/connection_pool.rb:357:in `check_out'
     # ./lib/mongo/server/connection_pool.rb:556:in `with_connection'
     # ./lib/mongo/server.rb:410:in `with_connection'
     # ./lib/mongo/operation/shared/executable.rb:55:in `dispatch_message'
     # ./lib/mongo/operation/shared/executable.rb:50:in `get_result'
     # ./lib/mongo/operation/shared/executable.rb:29:in `block (3 levels) in do_execute'
     # ./lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
     # ./lib/mongo/operation/shared/executable.rb:28:in `block (2 levels) in do_execute'
     # ./lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
     # ./lib/mongo/operation/shared/executable.rb:27:in `block in do_execute'
     # ./lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
     # ./lib/mongo/operation/shared/executable.rb:26:in `do_execute'
     # ./lib/mongo/operation/shared/executable.rb:38:in `execute'
     # ./lib/mongo/operation/shared/op_msg_or_command.rb:27:in `execute'
     # ./lib/mongo/database.rb:178:in `block in command'
     # ./lib/mongo/cluster.rb:799:in `with_session'
     # ./lib/mongo/client.rb:825:in `with_session'
     # ./lib/mongo/database.rb:171:in `command'
     # ./spec/support/cluster_config.rb:145:in `determine_cluster_config'
     # ./spec/support/cluster_config.rb:17:in `server_version'
     # ./spec/support/cluster_config.rb:35:in `fcv_ish'
     # ./spec/spec_helper.rb:22:in `block (2 levels) in <top (required)>'

Finished in 0.02404 seconds (files took 0.41665 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/mongo/address_spec.rb:247 # Mongo::Address#socket when providing a DNS entry that resolves to both IPv6 and IPv4 attempts to use IPv6 and fallbacks to IPv4
```

**Comment by egiurleo** [comment]
@aayushagrawal135 it looks like that's not the same error message that you shared before. I usually get the message `User root-user (mechanism: scram) is not authorized to access ruby-driver` when I try to run individual tests without preparing the test suite (running `bundle exec rake spec:prepare` to set up the right test users). Could you try running the test again after you run `bundle exec spec:prepare` and send me the stack trace when the test fails because it was expecting 127.0.0.1 but it got ::2?

**Pull request merged**
