### PR TITLE
RUBY-2578 Disable Ubuntu 14.04 based configs

### PR DESCRIPTION
**Pull request by comandeo**
https://jira.mongodb.org/browse/RUBY-2758

### CODE REVIEW

**Comment by comandeo** [comment]
I suggest merging this one before others, so that we have green CI baseline.

**Comment by p-mongo** [comment]
Is the ticket referenced correct? https://jira.mongodb.org/browse/RUBY-2576

**Comment by comandeo** [comment]
> Is the ticket referenced correct? https://jira.mongodb.org/browse/RUBY-2576

No, it should be https://jira.mongodb.org/browse/RUBY-2758. Fixed PR title and added a comment with the issue number

**Review by p-mongo — APPROVED** [review]
Let's merge and fix immediately.

**Pull request merged**
