### PR TITLE
MONGOID-5304: Add Rubocop static code analyzer

### PR DESCRIPTION
**Pull request by johnnyshields**
This PR adds a static code analyzer (Rubocop) to the project, as required by MongoDB's [Technical and Organizational Security Measures](https://www.mongodb.com/technical-and-organizational-security-measures).

It is integrated with Github CI. To add it to Evergreen, simply run this shell command (only needs to be run once for the entire suite; not dependent on Ruby version, etc.) I've done a draft of Evergreen integration in this PR, but it may not work as I cannot run Evergreen myself.

```
bundle exec rake rubocop
```

Refer to the related [Mongoid PR](https://github.com/mongodb/mongoid/pull/5243) for further explanation.

### CODE REVIEW

**Comment by johnnyshields** [comment]
Ready to merge, please check Evergreen setup works.

**Review by p-mongo — CHANGES_REQUESTED** [review]
Hi @johnnyshields ,

As per https://jira.mongodb.org/browse/MONGOID-5304, if you would like to adjust this PR to only enable non-style/formatting checks, we will review it.

**Comment by johnnyshields** [comment]
@p-mongo this is updated as per your comments in https://jira.mongodb.org/browse/MONGOID-5304

**Review by p-mongo — CHANGES_REQUESTED** [review]
After https://github.com/mongodb/bson-ruby/pull/284#pullrequestreview-977317484 is fixed please make this PR same as the bson-ruby one.

**Comment by johnnyshields** [comment]
@p-mongo Changes to the Rubocop file are done as requested (only Security in /lib dir)

**Comment by johnnyshields** [comment]
Removed `rake rubocop` from this PR.

**Review by comandeo — APPROVED** [review]
Looks good to me. I think that a Github action configuration is sufficient here, we do not really need to use evergreen.

**Comment by johnnyshields** [comment]
Awesome 🎉 !! Next step: start turning on cops and actually using it like Rails, etc. do :)

I will update my Rubocop PR for Mongoid as well. There's one for BSON too.

**Pull request merged**
