### PR TITLE
RUBY-1614 Use "local" read concern when asserting final collection st…

### PR DESCRIPTION
**Pull request by saghm**
…ate in transaction tests

### CODE REVIEW

**Comment by p-mongo** [comment]
I see that there are several failed test configurations, is there one which succeeded and also ran the tests which are being modified in this PR?

**Comment by saghm** [comment]
All of the 4.0 replica set variants successfully ran the transactions tests, which are the only ones touched by this commit. The failures are all pre-existing, dating back to [this commit](https://evergreen.mongodb.com/version/mongo_ruby_driver_2c5156f3b2f953a220796acbccf35d374129dfb9). Feel free to check the individual variant logs from this PR and the waterfall matrix on Evergreen for the driver to verify this.

**Comment by p-mongo** [comment]
Do you think more tests will pass in this PR now that https://github.com/mongodb/mongo-ruby-driver/pull/1328 has been merge?

**Comment by saghm** [comment]
Yep, rebasing to get that commit seems to have made it more green

**Pull request merged**
